#!/bin/bash

# a script to generate Fibonacci series where length of series is based on the user input.

echo 'enter the desired length of the fibonacci series'
read N
a=0
b=1

echo "The Fibonacci series is : "

for (( i=0; i<N; i++ ))
do
    echo -n "$a "
    fn=$((a + b))
    a=$b
    b=$fn
done











#using while loop


echo "How many number of terms to be generated ?"
read n
function fibonacci
{
  x=0
  y=1
  i=2
  echo "Fibonacci Series up to $n terms :"
  echo "$x"
  echo "$y"
  # -lt stands for equal to
  while [ $i -lt $n ]  
  do
      i=`expr $i + 1 `
      z=`expr $x + $y `
      echo "$z"
      x=$y
      y=$z
  done
}
r=`fibonacci $n`
echo "$r"
